# -*- coding: utf-8 -*-
"""Reverse_Geocode_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a25X_ArQxwBbBYPXrTyVmocOyV6Y6Xam
"""

from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError

def reverse_geocode(lat, lon):
    geolocator = Nominatim(user_agent="reverse_geocode_app")
    try:
        location = geolocator.reverse((lat, lon), exactly_one=True)
        return location.address if location else "Address not found"
    except (GeocoderTimedOut, GeocoderServiceError) as e:
        return str(e)

if __name__ == "__main__":
    # Example coordinates
    latitude = float(input(print ("The required value of latitude is = ")))
    longitude = float(input(print ("The required value of longitude is = ")))

    address = reverse_geocode(latitude, longitude)
    print("Address:", address)